/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  guint tmp_key;
  GtkWidget *file;
  GtkWidget *file_menu;
  GtkAccelGroup *file_menu_accels;
  GtkWidget *exit;
  GtkWidget *help;
  GtkWidget *help_menu;
  GtkAccelGroup *help_menu_accels;
  GtkWidget *about;
  GtkWidget *handlebox1;
  GtkWidget *toolbar1;
  GtkWidget *btnImport;
  GtkWidget *btnPlay;
  GtkWidget *btnStop;
  GtkWidget *tglWatch;
  GtkWidget *notebook1;
  GtkWidget *scrolledwindow1;
  GtkWidget *clist1;
  GtkWidget *col_Number;
  GtkWidget *col_Title;
  GtkWidget *col_Time;
  GtkWidget *col_Pathname;
  GtkWidget *col_Filename;
  GtkWidget *tab_List;
  GtkWidget *vbox2;
  GtkWidget *hbox3;
  GtkWidget *label_Search;
  GtkWidget *combo_Search;
  GtkWidget *combo_entry_Search;
  GtkWidget *btn_Search;
  GtkWidget *scrolledwindow2;
  GtkWidget *clist2;
  GtkWidget *find_col_Number;
  GtkWidget *find_col_Title;
  GtkWidget *find_col_Time;
  GtkWidget *find_col_Pathname;
  GtkWidget *find_col_Filename;
  GtkWidget *tab_Search;
  GtkWidget *hbox1;
  GtkWidget *statusbar1;
  GtkWidget *progressbar1;
  GtkAccelGroup *accel_group;

  accel_group = gtk_accel_group_new ();

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (window1), "window1", window1);
  gtk_window_set_title (GTK_WINDOW (window1), _("Search Xmms Playlist"));

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox1", vbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window1), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_ref (menubar1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "menubar1", menubar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);

  file = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file)->child),
                                   _("_File"));
  gtk_widget_add_accelerator (file, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (file);
  gtk_object_set_data_full (GTK_OBJECT (window1), "file", file,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file);
  gtk_container_add (GTK_CONTAINER (menubar1), file);

  file_menu = gtk_menu_new ();
  gtk_widget_ref (file_menu);
  gtk_object_set_data_full (GTK_OBJECT (window1), "file_menu", file_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file), file_menu);
  file_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menu));

  exit = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (exit)->child),
                                   _("E_xit"));
  gtk_widget_add_accelerator (exit, "activate_item", file_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (exit);
  gtk_object_set_data_full (GTK_OBJECT (window1), "exit", exit,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (exit);
  gtk_container_add (GTK_CONTAINER (file_menu), exit);

  help = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help)->child),
                                   _("_Help"));
  gtk_widget_add_accelerator (help, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, 0);
  gtk_widget_ref (help);
  gtk_object_set_data_full (GTK_OBJECT (window1), "help", help,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help);
  gtk_container_add (GTK_CONTAINER (menubar1), help);

  help_menu = gtk_menu_new ();
  gtk_widget_ref (help_menu);
  gtk_object_set_data_full (GTK_OBJECT (window1), "help_menu", help_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help), help_menu);
  help_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help_menu));

  about = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (about)->child),
                                   _("_About..."));
  gtk_widget_add_accelerator (about, "activate_item", help_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (about);
  gtk_object_set_data_full (GTK_OBJECT (window1), "about", about,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about);
  gtk_container_add (GTK_CONTAINER (help_menu), about);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_ref (handlebox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "handlebox1", handlebox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, TRUE, 0);

  toolbar1 = gtk_toolbar_new (GTK_ORIENTATION_HORIZONTAL, GTK_TOOLBAR_BOTH);
  gtk_widget_ref (toolbar1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "toolbar1", toolbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar1);
  gtk_toolbar_set_tooltips (GTK_TOOLBAR (toolbar1), FALSE);

  btnImport = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Import"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (btnImport);
  gtk_object_set_data_full (GTK_OBJECT (window1), "btnImport", btnImport,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnImport);
  gtk_container_set_border_width (GTK_CONTAINER (btnImport), 2);

  btnPlay = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Play"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (btnPlay);
  gtk_object_set_data_full (GTK_OBJECT (window1), "btnPlay", btnPlay,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnPlay);
  gtk_container_set_border_width (GTK_CONTAINER (btnPlay), 2);

  btnStop = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Stop"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (btnStop);
  gtk_object_set_data_full (GTK_OBJECT (window1), "btnStop", btnStop,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btnStop);
  gtk_container_set_border_width (GTK_CONTAINER (btnStop), 2);

  tglWatch = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_TOGGLEBUTTON,
                                NULL,
                                _("Watch"),
                                NULL, NULL,
                                NULL, NULL, NULL);
  gtk_widget_ref (tglWatch);
  gtk_object_set_data_full (GTK_OBJECT (window1), "tglWatch", tglWatch,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tglWatch);
  gtk_container_set_border_width (GTK_CONTAINER (tglWatch), 2);

  notebook1 = gtk_notebook_new ();
  gtk_widget_ref (notebook1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "notebook1", notebook1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook1);
  gtk_box_pack_start (GTK_BOX (vbox1), notebook1, TRUE, TRUE, 0);

  scrolledwindow1 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow1", scrolledwindow1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow1);
  gtk_container_add (GTK_CONTAINER (notebook1), scrolledwindow1);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow1), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist1 = gtk_clist_new (5);
  gtk_widget_ref (clist1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clist1", clist1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist1);
  gtk_container_add (GTK_CONTAINER (scrolledwindow1), clist1);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 0, 47);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 1, 198);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 2, 136);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 3, 129);
  gtk_clist_set_column_width (GTK_CLIST (clist1), 4, 103);
  gtk_clist_column_titles_show (GTK_CLIST (clist1));

  col_Number = gtk_label_new (_("Number"));
  gtk_widget_ref (col_Number);
  gtk_object_set_data_full (GTK_OBJECT (window1), "col_Number", col_Number,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (col_Number);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 0, col_Number);
  gtk_label_set_justify (GTK_LABEL (col_Number), GTK_JUSTIFY_RIGHT);

  col_Title = gtk_label_new (_("Title"));
  gtk_widget_ref (col_Title);
  gtk_object_set_data_full (GTK_OBJECT (window1), "col_Title", col_Title,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (col_Title);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 1, col_Title);
  gtk_label_set_justify (GTK_LABEL (col_Title), GTK_JUSTIFY_LEFT);

  col_Time = gtk_label_new (_("Time"));
  gtk_widget_ref (col_Time);
  gtk_object_set_data_full (GTK_OBJECT (window1), "col_Time", col_Time,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (col_Time);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 2, col_Time);
  gtk_label_set_justify (GTK_LABEL (col_Time), GTK_JUSTIFY_RIGHT);

  col_Pathname = gtk_label_new (_("Pathname"));
  gtk_widget_ref (col_Pathname);
  gtk_object_set_data_full (GTK_OBJECT (window1), "col_Pathname", col_Pathname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (col_Pathname);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 3, col_Pathname);
  gtk_label_set_justify (GTK_LABEL (col_Pathname), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (col_Pathname), TRUE);

  col_Filename = gtk_label_new (_("Filename"));
  gtk_widget_ref (col_Filename);
  gtk_object_set_data_full (GTK_OBJECT (window1), "col_Filename", col_Filename,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (col_Filename);
  gtk_clist_set_column_widget (GTK_CLIST (clist1), 4, col_Filename);
  gtk_label_set_justify (GTK_LABEL (col_Filename), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (col_Filename), TRUE);

  tab_List = gtk_label_new (_("Whole List"));
  gtk_widget_ref (tab_List);
  gtk_object_set_data_full (GTK_OBJECT (window1), "tab_List", tab_List,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tab_List);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), tab_List);

  vbox2 = gtk_vbox_new (FALSE, 0);
  gtk_widget_ref (vbox2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "vbox2", vbox2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (vbox2);
  gtk_container_add (GTK_CONTAINER (notebook1), vbox2);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox3);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox3", hbox3,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox2), hbox3, FALSE, TRUE, 0);

  label_Search = gtk_label_new (_("Search for :"));
  gtk_widget_ref (label_Search);
  gtk_object_set_data_full (GTK_OBJECT (window1), "label_Search", label_Search,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (label_Search);
  gtk_box_pack_start (GTK_BOX (hbox3), label_Search, FALSE, FALSE, 0);
  gtk_misc_set_padding (GTK_MISC (label_Search), 2, 0);

  combo_Search = gtk_combo_new ();
  gtk_widget_ref (combo_Search);
  gtk_object_set_data_full (GTK_OBJECT (window1), "combo_Search", combo_Search,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_Search);
  gtk_box_pack_start (GTK_BOX (hbox3), combo_Search, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (combo_Search), 2);

  combo_entry_Search = GTK_COMBO (combo_Search)->entry;
  gtk_widget_ref (combo_entry_Search);
  gtk_object_set_data_full (GTK_OBJECT (window1), "combo_entry_Search", combo_entry_Search,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (combo_entry_Search);

  btn_Search = gtk_button_new_with_label (_(" Search "));
  gtk_widget_ref (btn_Search);
  gtk_object_set_data_full (GTK_OBJECT (window1), "btn_Search", btn_Search,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (btn_Search);
  gtk_box_pack_start (GTK_BOX (hbox3), btn_Search, FALSE, FALSE, 2);

  scrolledwindow2 = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (scrolledwindow2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "scrolledwindow2", scrolledwindow2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scrolledwindow2);
  gtk_box_pack_start (GTK_BOX (vbox2), scrolledwindow2, TRUE, TRUE, 0);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (scrolledwindow2), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  clist2 = gtk_clist_new (5);
  gtk_widget_ref (clist2);
  gtk_object_set_data_full (GTK_OBJECT (window1), "clist2", clist2,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist2);
  gtk_container_add (GTK_CONTAINER (scrolledwindow2), clist2);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 0, 51);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 1, 198);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 2, 78);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 3, 129);
  gtk_clist_set_column_width (GTK_CLIST (clist2), 4, 103);
  gtk_clist_column_titles_show (GTK_CLIST (clist2));

  find_col_Number = gtk_label_new (_("Number"));
  gtk_widget_ref (find_col_Number);
  gtk_object_set_data_full (GTK_OBJECT (window1), "find_col_Number", find_col_Number,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (find_col_Number);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 0, find_col_Number);
  gtk_label_set_justify (GTK_LABEL (find_col_Number), GTK_JUSTIFY_RIGHT);

  find_col_Title = gtk_label_new (_("Title"));
  gtk_widget_ref (find_col_Title);
  gtk_object_set_data_full (GTK_OBJECT (window1), "find_col_Title", find_col_Title,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (find_col_Title);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 1, find_col_Title);
  gtk_label_set_justify (GTK_LABEL (find_col_Title), GTK_JUSTIFY_LEFT);

  find_col_Time = gtk_label_new (_("Time"));
  gtk_widget_ref (find_col_Time);
  gtk_object_set_data_full (GTK_OBJECT (window1), "find_col_Time", find_col_Time,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (find_col_Time);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 2, find_col_Time);
  gtk_label_set_justify (GTK_LABEL (find_col_Time), GTK_JUSTIFY_LEFT);

  find_col_Pathname = gtk_label_new (_("Pathname"));
  gtk_widget_ref (find_col_Pathname);
  gtk_object_set_data_full (GTK_OBJECT (window1), "find_col_Pathname", find_col_Pathname,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (find_col_Pathname);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 3, find_col_Pathname);
  gtk_label_set_justify (GTK_LABEL (find_col_Pathname), GTK_JUSTIFY_LEFT);

  find_col_Filename = gtk_label_new (_("Filename"));
  gtk_widget_ref (find_col_Filename);
  gtk_object_set_data_full (GTK_OBJECT (window1), "find_col_Filename", find_col_Filename,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (find_col_Filename);
  gtk_clist_set_column_widget (GTK_CLIST (clist2), 4, find_col_Filename);
  gtk_label_set_justify (GTK_LABEL (find_col_Filename), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (find_col_Filename), TRUE);

  tab_Search = gtk_label_new (_("Seach & Results"));
  gtk_widget_ref (tab_Search);
  gtk_object_set_data_full (GTK_OBJECT (window1), "tab_Search", tab_Search,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (tab_Search);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), tab_Search);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_ref (hbox1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "hbox1", hbox1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, FALSE, FALSE, 0);

  statusbar1 = gtk_statusbar_new ();
  gtk_widget_ref (statusbar1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "statusbar1", statusbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (statusbar1);
  gtk_box_pack_start (GTK_BOX (hbox1), statusbar1, TRUE, TRUE, 0);

  progressbar1 = gtk_progress_bar_new ();
  gtk_widget_ref (progressbar1);
  gtk_object_set_data_full (GTK_OBJECT (window1), "progressbar1", progressbar1,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (progressbar1);
  gtk_box_pack_start (GTK_BOX (hbox1), progressbar1, FALSE, FALSE, 0);

  gtk_signal_connect (GTK_OBJECT (exit), "activate",
                      GTK_SIGNAL_FUNC (gtk_main_quit),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (about), "activate",
                      GTK_SIGNAL_FUNC (on_about_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnImport), "clicked",
                      GTK_SIGNAL_FUNC (on_btnImport_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnPlay), "clicked",
                      GTK_SIGNAL_FUNC (on_btnPlay_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btnStop), "clicked",
                      GTK_SIGNAL_FUNC (on_btnStop_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "click_column",
                      GTK_SIGNAL_FUNC (on_clist1_click_column),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist1), "select_row",
                      GTK_SIGNAL_FUNC (on_clist1_select_row),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (combo_entry_Search), "activate",
                      GTK_SIGNAL_FUNC (on_combo_entry_Search_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (btn_Search), "clicked",
                      GTK_SIGNAL_FUNC (on_btn_Search_clicked),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist2), "click_column",
                      GTK_SIGNAL_FUNC (on_clist1_click_column),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (clist2), "select_row",
                      GTK_SIGNAL_FUNC (on_clist1_select_row),
                      NULL);

  gtk_window_add_accel_group (GTK_WINDOW (window1), accel_group);

  return window1;
}

